iconsdir = $(datadir)/icons/hicolor/32x32
icons_appsdir = $(iconsdir)/apps
icons_actionsdir = $(iconsdir)/actions

dist_icons_apps_DATA =							\
	classviewer-class.svg						\
	classviewer-import.svg						\
	classviewer-macro.svg						\
	classviewer-member.svg						\
	classviewer-method.svg						\
	classviewer-namespace.svg					\
	classviewer-other.svg						\
	classviewer-struct.svg						\
	classviewer-type.svg						\
	classviewer-var.svg							\
	geany.png

dist_icons_actions_DATA =						\
	geany-build.png								\
	geany-close-all.png							\
	geany-save-all.png
